# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myproject < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/angshumanHalder/auto-test-go/releases/download/v0.0.3/auto-test-go_0.0.3_Darwin_arm64.tar.gz"
      sha256 "63a156f820dd58ea3d05e366a1eddfcfdbf1dd92f3da2aa9c421a08f48daee91"

      def install
        bin.install "auto-test-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/angshumanHalder/auto-test-go/releases/download/v0.0.3/auto-test-go_0.0.3_Linux_arm64.tar.gz"
      sha256 "16bdae191eff30a90f0038b85898ea7dff27263dd6d40304bedec0d31b2ec58a"

      def install
        bin.install "auto-test-go"
      end
    end
  end
end
